### ISSUE TITLE
Run in Github Actions

### ISSUE THREAD

**Issue by markwsac** [RLesur/crrri#106]
Thanks for this lovely package. Does it require any dependency (other than dependent R packages) if run in Github Actions? I mean do we need to add anything other than  `R -e 'install.packages("crrri")'` Thanks in anticipation!

**Comment by RLesur** [comment]
Thanks for the compliment, @markwsac! We use GitHub actions for testing crrri (see https://github.com/RLesur/crrri/blob/master/.github/workflows/R-CMD-check.yaml) and did not have to install anything: Chrome is alteady installed in GitHub Actions runners.

**Comment by markwsac** [comment]
Thanks for your response. Very helpful. After posting my original question I saw your response here #96  which says chrome needs to be installed for mac?

**Comment by RLesur** [comment]
> I saw your response here #96 which says chrome needs to be installed for mac?

Some times ago, Chrome was not installed on mac runners. But now, it is available by default (see https://github.com/actions/virtual-environments/blob/main/images/macos/macos-11.0-Readme.md and https://github.com/actions/virtual-environments/blob/main/images/macos/macos-10.15-Readme.md).

**Comment by cderv** [comment]
@markwsac did you try already to use it in GHA without success ? 
If so, do not hesitate to share more so we can help. 

Thanks!
