### ISSUE TITLE
Upload File

### ISSUE THREAD

**Issue by markwsac** [RLesur/crrri#109]
Thanks for this useful package.  Much appreciated!

Just wondering if possible to upload file via the package.

**Comment by cderv** [comment]
Unfortunately, I don't know. 

If you can find example of such usage with the Chrome devtool protocol, either using the `chrome-remote-interface` or puppeteer, we could probably help translate. 

Maybe someone knows about that, so I'll this that open for anyone to jump in.

**Comment by markwsac** [comment]
Thanks for your response and open for support. This link seems to be relevant - https://github.com/puppeteer/puppeteer/issues/5499

DOM$setFileInputFiles(list(file) should work but not sure what's going wrong here, might be related to the site when tried with chromote package and executed "view", it opens up the page but not opening dialogue box of selecting file when clicking "upload" button manually. @RLesur - Your wisdom would be highly appreciated!
