### ISSUE TITLE
reject or promise_reject ?

### ISSUE THREAD

**Issue by cderv** [RLesur/crrri#12]
@RLesur I do not find where `reject` comes from ? 

https://github.com/RLesur/crrri/blob/0f0b611655038291d042d6627ac55b9e737c7e07/R/chr_connect.R#L61

There is a [promise_reject](https://rstudio.github.io/promises/reference/promise_resolve.html) in promises but no more `reject`. Is this the same ? 

I think there are some namespace missing but I am not sure. 

I hope it is not obvious...

**Comment by RLesur** [comment]
this is an argument of the lambda function that is passed to `promises::promise()`

**Comment by RLesur** [comment]
naming this function `reject` is a convention (I think we must keep it since it is widely adopted). You can choose the name you want. There is no namespace involved.

**Comment by RLesur** [comment]
are you asking this question in link with #10? If this the case, we don't have to apply `debugme` for these messages: handling with rejected promises is the job of high-level 📦 devs. They will choose to inform their users or not when the promise is rejected.

**Comment by cderv** [comment]
Ok perfect. Still new in promises - i forgot. yes I am working on message. I am good now.
