### ISSUE TITLE
do not write work dir for chrome in R work dir? 

### ISSUE THREAD

**Issue by cderv** [RLesur/crrri#16]
currently `work_dir` is generated with a sample name in the current working directory. Is this necessary to be in the R working dir or can we move it ? 

I think it would be better to put this folder, either in temporary directory for Rsession if not persistence is needed or in user apps directory (using [rappdir](https://github.com/r-lib/rappdirs)

I think about that because after playing a few times with the package I have plenty of folder I need to remove and that are in the middle of other folder.

Temp directory would be nice but it was tried for decapitated and seems to be issue with it. see
https://github.com/hrbrmstr/decapitated#working-around-headless-chrome--os-security-restrictions
We could also borrow decapitated choice to write everything in a special folder in user home. 

I can work on something with rappdir otherwise

**Comment by RLesur** [comment]
I agree that we can improve the location of `work_dir`. However, I am surprised that the folders are not automatically suppressed.

**Comment by cderv** [comment]
I think it is when something goes wrong and not closes properly. I can try to reproduce it. 
In all case I'll move to a dir that is not is the current working dir, and I'll keep an eye is deleted or not.

**Comment by cderv** [comment]
it uses now rappdirs package to store chrome user data in `rappdirs::user_data_dir(appname = "r-crrri")`. 
In this folder, one folder will be created by chrome connection. 

Some tests have shown that it deletes correctly.
