### ISSUE TITLE
Add a wrapper for base64 encoded data

### ISSUE THREAD

**Issue by cderv** [RLesur/crrri#22]
Currently, this is possible using `jsonlite::base64_dec` but you need to know how to write this

```r
Page.printToPDF() %...T>% { 
        .$result$data %>% base64_dec() %>% writeBin(paste0(names(url), ".pdf")) 
      }
```

```r
  Page.captureScreenshot(format = "png", fromSurface = TRUE) %...T>% {
    .$result$data %>% jsonlite::base64_dec() %>% writeBin("test.png")
  }
```

Something like `crrri:::write_base64 `
```r
write_base64 <- function(promise, con) {
    promise %...T>% {
        .$result$data %>% jsonlite::base64_dec() %>% writeBin(con)
    }
}
```
or without pipe

```r
write_base64 <- function(promise, con) {
    data <- promise$result$data
    write <- promises::then(promise,
        raw <-  jsonlite::base64_dec(data) 
        writeBin(raw, con)
   promise::then(write, 
       function(value) promise
    )
}
```

It would be a side effect function, (like `purrr::walk`) and return the promise from the LHS.

**Comment by cderv** [comment]
This is working as expected with
```r
write_base64 <- function(promise, con) {
    promise %...T>% {
        .$result$data %>% jsonlite::base64_dec() %>% writeBin(con)
    }
}
```
and a correct non pipe equivalent 
```r
write_base64 <- function(promise, con) {
  write <- promises::then(promise, 
                          function(value) {
                            data <- value$result$data                      
                            raw <-  jsonlite::base64_dec(data) 
                            writeBin(raw, con)
                          })
  promises::then(write, 
                function(value) promise
  )
}
```

Could be a useful wrapper for all the print to file feature.

**Comment by RLesur** [comment]
Great! The only question I have is: why use the T pipe (or replicate its behavior) inside the `write_base64` function? in this example, there is no problem. But it could lead to a less intuitive interface if it is used as in an intermediate step.

**Comment by RLesur** [comment]
I understand and this is a difficult choice. For instance, with a `data.frame`, `plot()` has only side effects and is always used with a T pipe. Would the user prefer to deal with a `plot()` function that returns the lhs? From my point of view, I prefer to deal with "pure" side effects functions and constrain myself to use the T pipe. I'm not sure to be representative for this question. We could ask the question to our friendly R users on grrr?

**Comment by cderv** [comment]
Yes we could ask. I am not 100% convinced of my choice, So i don't mind changing it to yours. 
If I understand correctly you prefer to leave the T pipe outside ? 
```r
... %>%
  Page.captureScreenshot(format = "png", fromSurface = TRUE) %T>% # or even %...T>% 
  write_base64("test.png") %>%
  # Close the chrome connextion
  finally(~ chr_disconnect(chrome_con)) %...!% {
    cat("Global error\n", .$message)
  }
```
Is that what you are saying ? 
Indeed it could be clearer and better for the long run.

**Comment by RLesur** [comment]
Yes, that's it! Sorry, I'm on my phone, not easy for writing code 😉

**Comment by cderv** [comment]
Considering our discussion on separate 📦, should it be on this one or the marionnette one ?

**Comment by RLesur** [comment]
Since this a helper for writing higher level functions, maybe here.
