### ISSUE TITLE
Export all promises functions or Depends ?

### ISSUE THREAD

**Issue by cderv** [RLesur/crrri#23]
Currently, we need systematically to do 

```r
library(crrri)
library(promises)
```
in order to access `finally()` for example, or `promice_race`.

`crrri` works heavily with `promises` and require this other :package: . Should we 

* leave as is 
* make crrri depends on promises 
* export a few more functions we know are required for good use of crrri (like `finally`)

**Comment by RLesur** [comment]
good point. I like the third one.

**Comment by cderv** [comment]
I think we can export almost all function :) 

At least

- [ ] `finally`
- [ ] `catch`
- [ ] `then`

Maybe 

- [ ] `promise_*` functions

**Comment by RLesur** [comment]
I agree. To be used, `crrri` relies heavily on promises and all the promises package functions (except `new_promise_domain()`) are useful.

**Comment by cderv** [comment]
Ok so we can export. To do just after merging the new API
