### ISSUE TITLE
Better Identify file created automatically

### ISSUE THREAD

**Issue by cderv** [RLesur/crrri#25]
I find it difficult to identify easily which files are created by the generator and which files are for our functions. We can't use subdirectories inside the `R` folder so it needs to be in the name. 

This is small improvement I know, but what do you think ? 

We could either reverse the naming scheme from the generated files:

* `***_commands` ➡️ `command_***`
* `***_events` ➡️ `events_***`

That way we'll have files regrouped in explorer.

Other solution: 

* add a new prefix like `DP_***` to identify files with functions from devtools protocol.
* add a prefix like `crrri_***` to files that are not generated automatically...

What do you think?

**Comment by RLesur** [comment]
I have the same problem :smile:
Surely, we can improve file naming. 
I like your first proposal (`commands_` and `events_` prefix).
