### ISSUE TITLE
Clarify generator code with templating like logic ?

### ISSUE THREAD

**Issue by cderv** [RLesur/crrri#3]
I think it is not an heavy dependency and that maybe it could help clarify the generator code.
Clarifying the generation for R file could help for maintenance in the long run.
I'll try to look into it and PR something to see how it looks.

**Comment by RLesur** [comment]
No problem. Moreover, packages used in the generator do not create dependencies (they are ignored when the package is built).

**Comment by cderv** [comment]
I think I choose the wrong horse this morning... I believed it would simplified things but I am not so sure. 
However, templating should be a good way to clarify the generation process for future maintenance. I'll leave this open.

**Comment by cderv** [comment]
I close this for now as we are moving toward a new API in #40 and we do not generate code the same way
