### ISSUE TITLE
Can't access `.$result$root$nodeId` from `DOM.getDocument()`

### ISSUE THREAD

**Issue by juba** [RLesur/crrri#30]
The following code aims to dump the DOM of a web page :

```r
url <- "https://www.r-project.org/"
chrome <- chr_connect(bin = "google-chrome", headless = FALSE)
gd <- chrome %>% 
  Page.enable() %>% 
  DOM.enable() %>%
  Page.navigate(url) %>% 
  Page.loadEventFired() %>%
  DOM.getDocument()

gd %>%   
  DOM.getOuterHTML(nodeId = .$result$root$nodeId)
```

But it fails at `DOM.getOuterHTML(nodeId = .$result$root$nodeId)` with `Error: Invalid parameters(code -32602)`

It does work when giving a `nodeId` directly : 

```r
gd %>%   
  DOM.getOuterHTML(nodeId = 1)
```

And the `.$result$root$nodeId` value is correct : 

```r
gd %...>% {
  print(.$result$root$nodeId)
}
```

**Comment by RLesur** [comment]
I fixed the issue. The only mean for reusing the previous result is by using a formula:

    gd %>% DOM.getOuterHTML(nodeId = ~ .res$root$nodeId)

or

    gd %>% DOM.getOuterHTML(nodeId = ~ .$root$nodeId)

**Comment by juba** [comment]
I can confirm it's fixed for me too. Thanks a lot !

**Comment by cderv** [comment]
Pour référence, je me suis servi de cet exemple pour tester mes recherches sur la seconde API basée sur EventEmitter sans promises
https://gist.github.com/cderv/67d7ad8998559f2ce14b4eb4bb852fd1
