### ISSUE TITLE
Offer functions to setup and find chrome

### ISSUE THREAD

**Issue by cderv** [RLesur/crrri#37]
inspired by 

* `pagedown::find_chrome()` (would remove a suggest just for that in vignette)
* `decapitated` 📦  that offers to download a portable chrome. I use that and it works very well. 

For crrri, as a low level 📦 we could also assume that installation and configuration must be done by the user without any help from crrri. Just some documentation in README.

**Comment by ColinFay** [comment]
I second that idea.

Would be nice to have an error message here suggesting to launch `find_chrome()`: 

``` r 
> chrome <- Chrome$new() 
Running  --no-first-run --headless \
  '--user-data-dir=/Users/colin/Library/Application Support/r-crrri/chrome-data-dir-zlfusejq' \
  '--remote-debugging-port=9222'
Error: Cannot launch Chrome. Please check your system configuration.
```

I feel like `Please check your system configuration.` is a little bit cryptic, when what the function needs is the path to the chrome bin, so something like:

```r
Error: Cannot launch Chrome. Please add the path to your Chrome bin, you can trry and find it with `find_chrome()`.
```

Depending on `pagedown()` for that only function seems a little bit too much though.

**Comment by RLesur** [comment]
@ColinFay Thanks for the suggestion!

**Comment by cderv** [comment]
We still are missing a `download_chromium` like in decapitated: 
https://github.com/hrbrmstr/decapitated/blob/master/R/download-chromium.R

@hrbrmstr you suggested a fix version in decapitated from googleapi. 
I found later this website (https://chromium.woolyss.com/#notes) where there are several portable versions that where useful for me on windows. what do you think of this source ? 
We could either document the installation there or update you download_chromium function.

**Comment by cderv** [comment]
@RLesur do you think we can borrow the `find_chrome` function ? or should we rewrote it our way ? 
It seems useful and that configuring is not enough for users.

**Comment by RLesur** [comment]
**pagedown** license is MIT. There is no problem in reusing the source with appropriate credits.
The only point is that we should use a different function name to avoid conflicts.

**Comment by cderv** [comment]
This confirms what thought. 👍 
name idea: 
* `chrome_find` ? 😄  
* `find_chrome_binary` ?
* `guess_chrome_path` ?

**Comment by RLesur** [comment]
+1 for `find_chrome_binary()`

**Comment by cderv** [comment]
@ColinFay there is now a `find_chrome_binary()` function that will guess like that the one in pagedown but also use `HEADLESS_CHROME` env var if set.
