### ISSUE TITLE
Message when loading crrri (R CMD check NOTE)

### ISSUE THREAD

**Issue by RLesur** [RLesur/crrri#48]
There is a note in check https://travis-ci.org/RLesur/crrri/builds/524212680#L1012-L1017

```
* checking R code for possible problems ... NOTE
File ‘crrri/R/zzz.R’:
  .onLoad calls:
    packageStartupMessage("It seems you have this package in your DEBUGME variable,",     "but you have not install the debugme package yet.\n", "You need to install it to the the log messages.")
See section ‘Good practice’ in '?.onAttach'.
```
I have no idea for a turnaround.

**Comment by cderv** [comment]
I'll look into it.

**Comment by cderv** [comment]
Apparently you can't use `packageStartupMessage` in `.onLoad`, only in `.onAttach`. Surprisingly the doc is not clear about that. 

Anyhow, we don't need this so I will simplify
