### ISSUE TITLE
check if bin exist chr_init

### ISSUE THREAD

**Issue by cderv** [RLesur/crrri#5]
if not, an error should be thrown as soon as we know it will fail. 
Right now, it fails late

```r
chr_connect()
```

throws

```
Cannot find the websocket entrypoint of Chrome headless.
Closing headless Chrome...
<Promise [rejected: simpleError]>
Warning messages:
1: In open.connection(con, "rb") :
  InternetOpenUrl failed: 'Impossible d'établir une connexion avec le serveur'
2: In chr_kill(chr_process, work_dir) : attempt to apply non-function
Unhandled promise error: Command not found
```

I would expect a nice message about `google-chrome` not found

**Comment by RLesur** [comment]
Since we needed to use promises for the connexion (it was necessary for using `%>%`), the connexion process code is not satisfying: it should to be rewritten with promises.

**Comment by cderv** [comment]
closed by https://github.com/RLesur/crrri/commit/c25cf13ed8baba49f5201d765f35b763cbac6a11
