### ISSUE TITLE
Runtime Evaluate Await Javascript Promises

### ISSUE THREAD

**Issue by theIssuer** [RLesur/crrri#79]
I use runtime$evaluate to run a javascript. In this javascript I have a promise that waits for an iframe to load, and then returns the content of the iframe.

However, the runtime$evaluate doesn't wait for the javascript promise to resolve even though I put await in the javascript. Here is my javascript code:

`const MENU_FRAME = document.getElementById('frleft'),
              MAIN_FRAME = document.getElementById('i9999'),
              MAIN_WDW = MAIN_FRAME.contentWindow,
              LNK = MENU_FRAME.contentWindow.document.querySelector('#trMenu3 a[title=\"Affiliate Tree\"]');

        const EVT = document.createEvent('MouseEvents');

        EVT.initEvent('click', true, true);
        EVT.synthetic = true;

        const P = new Promise(function(ff) {
          MAIN_FRAME.addEventListener('load', function(evt) {
            ff();
          }, {
            once: true
          });
        });

        LNK.dispatchEvent(EVT, true);

        await P.then(function() {
          const MAIN_DOC = MAIN_WDW.document,
                IPT = MAIN_DOC.querySelector('#Label7 + input'),
                SEARCH_BTN = MAIN_DOC.getElementById('btnSearch');

          IPT.value = '1234';

          const EVT = MAIN_DOC.createEvent('MouseEvents');

          EVT.initEvent('click', true, true);
          EVT.synthetic = true;

          const P = new Promise(function(ff) {
            MAIN_FRAME.addEventListener('load', function(evt) {
              ff();
            }, {
              once: true
            });
          })

          SEARCH_BTN.dispatchEvent(EVT, true);

          return P;
        }).then(function() {
          return MAIN_WDW.document.documentElement.outerHTML;
        });`

The runtime$evaluate gives me this error: Unhandled promise error: argument is of length zero.

If someone can help me how to scrape iframes or how to make this javascript promise to work with crrri, it would be greatly appreciated.

**Comment by cderv** [comment]
I am not a JS expert but I can look into it. It is difficult to help without being able to reproduce. is it possible to make a reproducible example we could run on our side ? 

Also, did you test this JS code in Chrome Devtools console in a browser to see if the JS code already does what you expect ? This would help to isolate a JS issue or a crrri issue. 

If in crrri, you can activate some logging messages by installing and activating `debugme` for `crrri` 
See [in Readme](https://github.com/RLesur/crrri#logging-messages). That could help see where the error happens.

**Comment by theIssuer** [comment]
the code works in chrome console.
But in runtime$evaluate, the code doesn't run at all if I have `await` in my javascript code. But if I remove `await`, the javascript code runs, but then the evaluate function doesn't wait for the javascript promise to resolve.

**Comment by theIssuer** [comment]
Looks like `await` is not supported in the top level.
I need to block the evaluate function from resolving until my javascript promise is resolved and returned a value.

Any way to do that or any other more elegant way to scrape iframes?

**Comment by cderv** [comment]
I think this is indeed something to do with how the chrome devtool protocol is working. 
When using domain Runtime, method Evaluate, there is some stuff to take care. 
There is some examples [there](https://github.com/cyrus-and/chrome-remote-interface/issues/110#issuecomment-296163726) that could maybe help to rewrite your js code. 

About scraping iframe, if you found some example on how to do it with CDP using another tool than crrri (pupetteer or chrome-remote-interface, or other), we can help write it with crrri. 
I don't know specifically how to scrape iframes. Sorry.

**Comment by theIssuer** [comment]
Thanks.

I resolved it by creating an R promise that checks the javascript promise every 1 second. Then resolving the R promise once the javascript promise is resolved.

**Comment by RLesur** [comment]
@theIssuer 
> Looks like _await_ is not supported in the top level.

Sure, see https://developer.mozilla.org/docs/Web/JavaScript/Reference/Operators/await

FWIW, I've implemented the following strategy in `pagedown::chrome_print()` for non Paged.js documents (see https://github.com/rstudio/pagedown/blob/574beb49bf6393857f3c7563c3535d84ac1e8bbc/R/chrome.R#L321-L352):
- create a binding with [`Runtime.addBinding`](https://chromedevtools.github.io/devtools-protocol/tot/Runtime#method-addBinding), see [here](https://github.com/rstudio/pagedown/blob/574beb49bf6393857f3c7563c3535d84ac1e8bbc/R/chrome.R#L323-L324)
- [create a promise in the execution context](https://github.com/rstudio/pagedown/blob/574beb49bf6393857f3c7563c3535d84ac1e8bbc/R/chrome.R#L330-L331) (in `pagedown::chrome_print()`, this promise is [`pagedownReady`](https://github.com/rstudio/pagedown/blob/574beb49bf6393857f3c7563c3535d84ac1e8bbc/inst/resources/js/chrome_print.js#L43))
- call the binding when the promise is resolved, see [here](https://github.com/rstudio/pagedown/blob/574beb49bf6393857f3c7563c3535d84ac1e8bbc/R/chrome.R#L348-L349)
- when the event [`Runtime.bindingCalled`](https://chromedevtools.github.io/devtools-protocol/tot/Runtime#event-bindingCalled) fires, execute other actions
