### ISSUE TITLE
Rethink API toward OOP ? 

### ISSUE THREAD

**Issue by cderv** [RLesur/crrri#8]
OOP was on the table but not chosen for this first draft. Mentioned in #1 

## Advantage of OOP
   * More secure
   * More suited for low-level api
   * Adapted to Domain and methods per domain (ex `Page$captureSnapshot`())

## Advantage of current approach
   * The closest from the protocol and how it is used in JS
   * Better documentation in R
   * Easier to generate "automagically" 😉 
   * works well with Promises and Websockets

Main Question about OOP : 
+ How would it work with promises and websocket ? 

Leaving as is for now - we'll see on the run how this first draft is doing.

**Comment by RLesur** [comment]
I think we can implement now an API like this one:
``` r
chrome <- chr_connect(async = FALSE) # it is yet developed
chrome$Page$enable() # TODO
```
I think the best way would be to retrieve the remote protocol at `http://localhost:debug_port/json/protocol` and dynamically create the methods.

**Comment by cderv** [comment]
Isn't like a milestone for v0.2  and we should concentrate on current api and other idea ?

**Comment by RLesur** [comment]
As you prefer. The only benefit I see of an API like this one is for an interactive use of the protocol: many R devs are not still familiar with promises. It could be used for learning how DevTools works.
However, I definitely won't use such an API in production (because of callbacks).

**Comment by cderv** [comment]
I think for now promises is fine and it is a great way of learning them ;-)

**Comment by RLesur** [comment]
I've had a deeper look at puppeteer code.
Main parts of puppeteer relies on the node.js [`EventEmitter` class](https://nodejs.org/api/events.html). I found this class awesome.
I think it can be quite easy to implement with R6.
Here's a sketch (I've not implemented all the features).
``` r
EventEmitter <- R6::R6Class("EventEmitter",
  public = list(
    emit = function(eventName, ...) {
      callbacks <- private$callbacks[[eventName]]
      if (eventName == 'error' & length(callbacks) == 0)
          stop(...)
      if (length(callbacks) > 0)
        tryCatch(callbacks$invoke(...), 
                 error = function(e) self$emit('error', e))
      else
        invisible(NULL)
    },
    on = function(eventName, callback) {
      callbacks <- private$callbacks[[eventName]]
      if (length(callbacks) == 0)
        private$callbacks[[eventName]] <- Callbacks$new()
      self$emit('newListener', eventName, callback)
      private$callbacks[[eventName]]$register(callback)
      self
    },
    once = function(eventName, callback) {
      callbacks <- private$callbacks[[eventName]]
      if (length(callbacks) == 0)
        private$callbacks[[eventName]] <- Callbacks$new()
      remove_callback <- NULL
      new_callback <- function(...) {
        callback(...)
        remove_callback()
        self$emit('removeListener', eventName, callback)
      }
      remove_callback <- private$callbacks[[eventName]]$register(new_callback)
    },
    listenerCount = function(eventName) {
      length(private$callbacks[[eventName]])
    }
  ),
  private = list(
    callbacks = list()
  )
)

# from rstudio/websocket
Callbacks <- R6::R6Class(
  'Callbacks',
  private = list(
    .nextId = integer(0),
    .callbacks = 'environment'
  ),
  public = list(
    initialize = function() {
      # NOTE: we avoid using '.Machine$integer.max' directly
      # as R 3.3.0's 'radixsort' could segfault when sorting
      # an integer vector containing this value
      private$.nextId <- as.integer(.Machine$integer.max - 1L)
      private$.callbacks <- new.env(parent = emptyenv())
    },
    register = function(callback) {
      if (!is.function(callback)) {
        stop("callback must be a function")
      }
      id <- as.character(private$.nextId)
      private$.nextId <- private$.nextId - 1L
      private$.callbacks[[id]] <- callback
      return(function() {
        rm(list = id, pos = private$.callbacks)
      })
    },
    invoke = function(...) {
      # Ensure that calls are invoked in the order that they were registered
      keys <- as.character(sort(as.integer(ls(private$.callbacks)), decreasing = TRUE))
      callbacks <- mget(keys, private$.callbacks)
      
      for (callback in callbacks) {
        callback(...)
      }
    },
    count = function() {
      length(ls(private$.callbacks))
    }
  )
)
```
I think that the `DevToolsConnexion` class should inherit of the `EventEmitter` class instead of the `websocket::WebSocket` class (the websocket connexion would be a private method) : all the messages received by the websocket connexion would lead to a call of the `emit()` method.
The `DevToolsConnexion` class would have a `send()` method.
The advantages I saw in puppeteer is that it can be useful to implement domain classes (for higher level packages).
BTW, puppeteer defines a `CDPSession` class. I think that `Chrome Developer Protocol Session` is far more meaningful than `DevToolsConnexion`...

**Comment by cderv** [comment]
I like this. pretty clear. Nice idea to go look into Puppeteer 👍 

And on this I totally trust you 😉

**Comment by cderv** [comment]
You may already have seen it but I began working on eventEmitter R6 class in branch [feature/eventemitters](https://github.com/RLesur/crrri/tree/feature/eventemitters)

I did not put everything described in [events doc](https://nodejs.org/api/events.html) but we could. It misses currently the ability to remove some listeners. It may needs some adjustment in Callback R6 class. 
i will try to use eventEmitter in crrri now and if working properly we could discuss the need of a proper eventEmitter class like the one in node.js (in an other small 📦 ?). I found an [implementation ](https://github.com/Olical/EventEmitter) in JS for client side only - very instructive. 

Also, we used _callback_ as name a lot - shouldn't we talk about _Listener_ instead ? I find it more understandable. 😄

**Comment by cderv** [comment]
This is in good direction now in #40 and that once merged this will close this issue. Don't you think ?

**Comment by RLesur** [comment]
I agree.

**Comment by cderv** [comment]
I have put the keyword in the PR for automatic closing.
